import type { Metadata } from "next";
import { Source_Sans_3 } from "next/font/google";
import "./globals.css";
import SessionProvider from "./components/SessionProvider";

const sourceSans = Source_Sans_3({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "NowTed",
  description:
    "Generated by create next app & Developed by Gia Miminoshvili with ❤️",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sourceSans.className} bg-[#181818]`}>
        <SessionProvider>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
